export const Color = [
  { key: "bug", value: "#a6b91a" },
  { key: "dark", value: "#705746" },
  { key: "dragon", value: "#6f35fc" },
  { key: "electric", value: "#f7d02c" },
  { key: "fairy", value: "#d685ad" },
  { key: "fighting", value: "#c22e28" },
  { key: "fire", value: "#ee8130" },
  { key: "flying", value: "#a98ff3" },
  { key: "ghost", value: "#735797" },
  { key: "grass", value: "#7ac74c" },
  { key: "ground", value: "#e2bf65" },
  { key: "ice", value: "#96d9d6" },
  { key: "normal", value: "#a8a77a" },
  { key: "poison", value: "#a33ea1" },
  { key: "psychic", value: "#f95587" },
  { key: "rock", value: "#b6a136" },
  { key: "steel", value: "#b7b7ce" },
  { key: "water", value: "#6390f0" },
];
